apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidsgiver-mock-enhetsregisteret
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://arbeidsgiver-mock-enhetsregisteret.intern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 60
  readiness:
    path: /internal/isReady
    initialDelay: 60
  env:
    - name: SERVER_PORT
      value: "8080"
