apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidsgiver-mock-enhetsregisteret
  namespace: teamia
  labels:
    team: teamia
spec:
  image: ghcr.io/navikt/arbeidsgiver-mock-enhetsregisteret:621197be9090da5ee2b4e1aca4dd2694b357daab
  port: 8080
  ingresses:
    - https://arbeidsgiver-mock-enhetsregisteret.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 60
  readiness:
    path: /internal/isReady
    initialDelay: 60
  prometheus:
    enabled: true
    path: /arbeidsgiver-mock-enhetsregisteret/internal/actuator/prometheus
  env:
    - name: SERVER_PORT
      value: "8080"
