apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidsgiver-mock-enhetsregisteret
  namespace: pia
  labels:
    team: pia
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://arbeidsgiver-mock-enhetsregisteret.intern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 60
  readiness:
    path: /internal/isReady
    initialDelay: 60
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: SERVER_PORT
      value: "8080"
