name: Build and deploy
run-name: Build and deploy ~~ "${{ github.event.head_commit.message }}"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build, test and push docker image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Run tests
        run: ./gradlew test --info

  build-and-publish-image:
    name: Build and publish image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Build jar with Gradle
        run: ./gradlew clean build installDist
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamia
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          salsa: false
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy-to-dev:
    name: Deploy to dev-gcp
    needs: docker-build-push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ needs.build-and-publish-image.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev-gcp.yaml
